LANGUAGE_MODEL_BOW = "en_core_web_sm"
LANGUAGE_MODEL_EMBEDDINGS = "en_core_web_trf"

DATA_FOLDER_RAW = "raw"
DATA_FOLDER_NAME_PROCESSED = "processed"
DATA_FOLDER_NAME_POSITIVE = "GOOD"
DATA_FOLDER_NAME_NEGATIVE = "BAD"
DATA_FOLDER_NAME_NEUTRAL = "NEUTRAL"
